output_dir: seed_ckpt/
dataset:
  class: ScopeHB
  path: ~/Superfamily/GearNet/scop_data/Data/
  multitask: True
  transform:
    class: ProteinView
    view: residue

task:
  class: MultiTaskPrediction
  num_mlp_layer: 3
  mlp_batch_norm: True
  mlp_dropout: 0.5
  model:
    class: GearNetIEConv
    input_dim: 21 # node feature
    embedding_dim: 512
    hidden_dims: [512, 512, 512, 512, 512, 512]
    batch_norm: True
    concat_hidden: True
    short_cut: True
    readout: 'sum'
    num_relation: 5
    edge_input_dim: 57  #edge feature 20+20+11+1+num_relation
    num_angle_bin: 8
    layer_norm: True
    dropout: 0.2
    use_ieconv: True
  graph_construction_model:
    class: GraphConstruction
    # node_layers:
    #   - class: AlphaCarbonNode
    edge_layers:
      # - class: BondEdge
      - class: SequentialEdge
        max_distance: 2
      # - class: SpatialEdge
      #   radius: 10.0
      #   min_distance: 0
      # - class: KNNEdge
      #   k: 15
      #   min_distance: 0
    edge_feature: gearnet
  criterion: ce
  metric: ['acc']
  num_class: [12, 1483, 2391]
  # num_class: 2391


optimizer:
  class: Adam
  lr: 1.0e-4
  weight_decay: 5.0e-4
  # momentum: 0.98

scheduler:
  class: ReduceLROnPlateau
  factor: 0.6
  patience: 5

verbose: 0
engine:
  gpus: {{ gpus }}
  batch_size: 4
  log_interval: 250

# classifier: True

checkpoint: {{ ckpt }}

metric: accuracy [super]

train:
  num_epoch: 100
  save_step: 5
