output_dir: log_ckpt/
dataset:
  class: HBCATH
  path: ~/Superfamily/GearNet/CATH_DATA/
  multitask: True
  transform:
    class: ProteinView
    view: residue

task:
  class: MultiTaskPrediction
  num_mlp_layer: 3
  mlp_batch_norm: True
  mlp_dropout: 0.5
  model:
    class: GearNetIEConv
    input_dim: 21 # node feature
    embedding_dim: 512
    hidden_dims: [512, 512, 512, 512, 512, 512]
    batch_norm: True
    concat_hidden: True
    short_cut: True
    readout: 'sum'
    num_relation: 14
    edge_input_dim: 66  #edge feature 21+21+1+1+num_relation
    num_angle_bin: 8
    layer_norm: True
    dropout: 0.2
    use_ieconv: True
  graph_construction_model:
    class: GraphConstruction
    # node_layers:
    #   - class: AlphaCarbonNode
    edge_layers:
      - class: HBondEdge
        radius: 0
      - class: SequentialEdge
        max_distance: 2
      - class: SpatialEdge
        radius: 10.0
        min_distance: 5
      - class: KNNEdge
        k: 10
        min_distance: 5
    edge_feature: gearnet
  criterion: ce
  metric: ['acc']
  num_class: [5,43,1472,6631]
  # num_class: 2391


optimizer:
  class: Adam
  # 5e-4
  lr: 4.0e-5
  weight_decay: 5.0e-4
  # momentum: 0.98

scheduler:
  class: ReduceLROnPlateau
  factor: 0.6
  patience: 5

verbose: 0
engine:
  gpus: {{ gpus }}
  # 8
  batch_size: 8
  log_interval: 250

# classifier: True

checkpoint: {{ ckpt }}

metric: accuracy [h]

train:
  num_epoch: 100
  save_step: 5
